# Generated by Django 4.1.7 on 2023-04-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=50)),
                ("days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achieved", models.BooleanField()),
                ("note", models.TextField()),
                (
                    "human",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="soberapp.human"
                    ),
                ),
            ],
        ),
    ]
