# Generated by Django 4.1.7 on 2023-04-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soberapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="date_taken",
            field=models.CharField(default="", max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="human",
            name="phone",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
